#!/bin/sh
#NOTE:  ❄️20%  💿30% 

CACHEDIR="$HOME/.cache/swaybar"

time=$(date "+%a %b %d %H:%M")
battery=$(cat "$CACHEDIR/battery" 2>/dev/null || echo "Battery:Null")
bright=$(cat "$CACHEDIR/bright" 2>/dev/null || echo "Bright:Null")
microphone=$(cat "$CACHEDIR/microphone" 2>/dev/null || echo "Micr:Null")
volume=$(cat "$CACHEDIR/volume" 2>/dev/null || echo "Vol:Null")
network=$(cat "$CACHEDIR/network" 2>/dev/null || echo "Net:Null")

echo "${network}  ${volume}  ${microphone}  ${bright}  ${battery}  ${time}"
