general.import = ["~/.config/alacritty/themes/39light.toml"]

[env]
TERM_PROGRAM = "alacritty"

[window]
option_as_alt = "Both"
decorations = "Buttonless"
dynamic_padding = true
padding = { x = 0, y = 0 }
position = { x = 650, y = 250 }

[font]
size = 15
normal = { family = "IosevkaTerm Nerd Font Mono", style = "Regular" }
bold_italic = { style = "Bold Italic" }
italic = { style = "Italic" }
bold = { style = "Bold" }
offset = { x = 0, y = 7 }

[keyboard]
bindings = [
{ key = "【", mods = "Control", chars = "\u001B" }, # chars: Unicode
{ key = "s", mods = "Super", chars = "\u001bs" },
{ key = "c", mods = "Super", action = "Copy" },
{ key = "v", mods = "Super", action = "Paste" },
{ key = "q", mods = "Super", action = "Quit" },
]
