#!/bin/sh

BATTERY_PATH=$(for ps in /sys/class/power_supply/*; do
    [ -f "$ps/type" ] && grep -qi battery "$ps/type" && echo "$ps"
done | head -n 1)

battery="$(cat ${BATTERY_PATH}/capacity)%"
bstatus=$(cat ${BATTERY_PATH}/status)
if [ "$bstatus" = "Charging" ]; then
    bchar="⚡"
else
    bchar="🔋"
fi
echo ${bchar}${battery}
