#!/bin/sh

im=""
count=0
while [ "$count" -lt 10 ] && [ -z "$im" ] ;do
    count=$((count +1))
    im=$(fcitx5-remote -n 2>/dev/null)
    if [ -z "$im" ] ; then 
        sleep 1
    fi
done

im_icon="[NO]"
if [ "$im" = "rime" ]; then
    im_icon="🇨🇳"
elif [ "$im" = "keyboard-us" ];then
    im_icon="🇺🇲"
fi

echo "$im_icon"
