[flags]
basic = true
rate = 1000
battery = true
regex = true
read_only = true
process_command = true
case_sensitive = false
memory.cache_memory = true

[processes]
default_memory_value = true
columns = [
    "pid",
    "name",
    "state",
    "cpu%",
    "mem%",
    "user",
    "time",
    "tread",
    "twrite",
    # "gmem%",
    # "gpu%",
    # "read",
    # "write",
]

[styles.widgets]
selected_text = { colour = "white", bg_colour = "blue", bold = true }
text = { colour = "lightblue" }
