mixed-port: 53939 # HTTP(S) 和 SOCKS 代理混合端口
redir-port: 63939 # 透明代理端口，用于 Linux 和 MacOS
mode: rule
log-level: info
ipv6: true
allow-lan: false # 局域网连接
unified-delay: true # 开启统一延迟时，会计算 RTT，以消除连接握手等带来的不同类型节点的延迟差异
external-controller-unix: mihomo.sock
external-controller: 127.0.0.1:59393 # WebUI 控制端口
secret: "xx11"
external-ui: ./ui
geo-auto-update: true

profile:
    store-selected: true # 储存 API 对策略组的选择，以供下次启动时使用
    store-fake-ip: true # 储存 fakeip 映射表，域名再次发生连接时，使用原有映射地址

tun:
    enable: true
    # system 使用系统协议栈，可以提供更稳定/全面的 tun 体验，且占用相对其他堆栈更低
    # gvisor 通过在用户空间中实现网络协议栈，可以提供更高的安全性和隔离性，同时可以避免操作系统内核和用户空间之间的切换，从而在特定情况下具有更好的网络处理性能
    # mixed 混合堆栈，tcp 使用 system栈，udp 使用 gvisor栈，使用体验可能相对更好
    stack: mixed
    # 劫持所有dns解析请求
    dns-hijack:
        - "any:53"
        - "tcp://any:53"
    auto-route: true
    auto-detect-interface: true

#  # NOTE: ???? Clash DNS 请求逻辑：
#  # (1) 当访问一个域名时， nameserver 与 fallback 列表内的所有服务器并发请求，得到域名对应的 IP 地址。
#  # (2) clash 将选取 nameserver 列表内，解析最快的结果。
#  # (3) 若解析结果中，IP 地址属于 国外，那么 Clash 将选择 fallback 列表内，解析最快的结果。
#  # 注意：
#  # (1) 如果您为了确保 DNS 解析结果无污染，请仅保留列表内以 tls:// 开头的 DNS 服务器，但是通常对于国内没有太大必要。
#  # (2) 如果您不在乎可能解析到污染的结果，更加追求速度。请将 nameserver 列表的服务器插入至 fallback 列表内，并移除重复项。
dns:
    enable: true
    ipv6: false
    use-system-hosts: false # 是否查询系统 hosts
    prefer-h3: false # true 会导致国内 DNS 解析慢
    # 启用 DNS 服务并让其在 53 端口（这是绝大多数操作系统将 DNS 解析报文发送到的端口）监听来自任意网络界面的 DNS 请求。
    # 如果你的设备并不需要向其他设备提供解析服务 将0.0.0.0:53 改为 127.0.0.1:53 仅监听本机的 DNS 解析报文。
    listen: 127.0.0.1:53
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    fake-ip-filter-mode: blacklist
    # 黑名单里的不会返回fakeip ,以下都为匹配局域网规则
    fake-ip-filter:
        - "*"
        - "+.lan"
        - "+.local"
    # 默认DNS, 用于解析DNS服务器的域名, 必须为IP (?确保国内可访问)
    default-nameserver:
        - 119.29.29.29 #tencent
        - 223.5.5.5 #ali
    # 代理节点域名解析服务器，仅用于解析代理节点的域名
    proxy-server-nameserver:
        - https://doh.pub/dns-query
    # 优先于 nameserver/fallback 查询 可使用 geosite
    nameserver-policy:
        "geosite:cn,private,apple@cn": # apple@cn
            - https://doh.pub/dns-query
            - https://dns.alidns.com/dns-query
        "geosite:!cn,!private":
            - "tls://dns.google"
            - "tls://cloudflare-dns.com"
    nameserver:
        - "tls://8.8.4.4#dns"
        - "tls://1.0.0.1#dns"
    # 用于 direct 出口域名解析的 DNS 服务器，如果不填则遵循 nameserver-policy、nameserver 和 fallback 的配置
    direct-nameserver:
        - https://doh.pub/dns-query
        - https://dns.alidns.com/dns-query
    # fake ip 不需要配置fallback, redir-host遗留产物

proxy-providers:
    provider1:
        type: file
        path: ./proxy_providers/proxy_1.yaml
        health-check:
            enable: true
            url: https://www.gstatic.com/generate_204
            interval: 300
            timeout: 1000
            lazy: true
    provider2:
        type: file
        path: ./proxy_providers/proxy_2.yaml
        health-check:
            enable: true
            url: https://www.gstatic.com/generate_204
            interval: 300
            timeout: 1000
            lazy: true

proxy-groups:
    - name: PROXY-1
      type: select
      use:
          - provider1

    - name: PROXY-2
      type: select
      use:
          - provider1

    - name: PROXY-3
      type: select
      use:
          - provider2
      proxies:
          - DIRECT

    - name: PROXY
      type: select
      proxies: [PROXY-1, PROXY-2, PROXY-3, DIRECT]

    - name: AI
      type: select
      proxies: [PROXY-1, PROXY-2, PROXY-3]

    - name: MEDIA-CN
      type: select
      proxies: [DIRECT, PROXY-1, PROXY-2, PROXY-3]

    - name: Apple-CN
      type: select
      proxies: [DIRECT, PROXY-1, PROXY-2, PROXY-3]

    - name: MS-CN
      type: select
      proxies: [DIRECT, PROXY-1, PROXY-2, PROXY-3]

rules:
    - GEOSITE,category-ads-all,REJECT
    # CN Media
    - GEOSITE,bilibili,MEDIA-CN
      # AI
    - GEOSITE,openai,AI
    - GEOSITE,google-gemini,AI
      # common
    - GEOSITE,github,PROXY
    - GEOSITE,twitter,PROXY
    - GEOSITE,youtube,PROXY
    - GEOSITE,steam,PROXY
    - GEOSITE,spotify,PROXY
    - GEOSITE,pixiv,PROXY
    - GEOSITE,google,PROXY
    - GEOSITE,google-cn,PROXY # Google CN 不走代理会导致香港等地区节点 Play Store 异常
      # CN Apple & MS
    - GEOSITE,apple@cn,Apple-CN
    - GEOSITE,apple,PROXY
    - GEOSITE,microsoft@cn,MS-CN
    - GEOSITE,microsoft,PROXY
      # CN site
    - GEOSITE,cn,DIRECT
      # other no CN site
    - GEOSITE,geolocation-!cn,PROXY
    - GEOIP,private,DIRECT,no-resolve # lan 不用dns 解析
    - GEOIP,twitter,PROXY
    - GEOIP,google,PROXY
    - GEOIP,cn,DIRECT
    - MATCH,PROXY
