if [ -n "$TERM_PROGRAM" ] ; then
    [ ! -f "$HOME/.hushlogin" ] && touch "$HOME/.hushlogin" #don't show last login info
    [ ! -n "$NOFISH" ] && command -v fish >/dev/null 2>&1 && exec fish
fi

set -o emacs
set bell-style none
shopt -s autocd
export CLICOLOR=1
export PS1='\n\u@\h:\[\e[34m\]\w\[\e[0m\]\n\$ '
