[ -f "$HOME/.profile" ] && . "$HOME/.profile" 
[ "$XDG_SESSION_TYPE" = "x11" -a -f "$HOME/.xinitrc" ] && . "$HOME/.xinitrc"

case "$0" in
    -*)
        . "$HOME/.bashrc"
        if [ -z "$WAYLAND_DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ] ; then
           exec sway
        fi
        ;;
esac
