# [ ! -f "$HOME/.hushlogin" ] && touch "$HOME/.hushlogin" #don't show last login info
# [ ! -n "$NOFISH" -a -n "$TERM_PROGRAM" ] && command -v fish >/dev/null 2>&1 && exec fish
#
# setopt emacs
# setopt AUTO_CD
# unsetopt BEEP
# export CLICOLOR=1
# export PS1=$'%n@%m:\e[0;34m%~\e[0m\n$ '
