[ ! -f "$HOME/.hushlogin" ] && touch "$HOME/.hushlogin" #don't show last login info
[ -n "$SSH_TTY" ] && command -v fish >/dev/null 2>&1  && exec fish
[ -n "$DISPLAY" -o -n "$TERM_PROGRAM" ] && command -v fish >/dev/null 2>&1 && fish

setopt emacs
setopt AUTO_CD
unsetopt BEEP
export CLICOLOR=1
export PS1=$'%n@%m:\e[0;36m%~\e[0m$ '
