[colors.primary]
background = "#FFFFFF"
foreground = "#000000"
[colors.normal]
black      = "#000000"
red        = "#C33720"
green      = "#009966"
yellow     = "#d9b002"
blue       = "#0000B2"
magenta    = "#B200B2"
cyan       = "#05A5B3"
white      = "#BFBFBF"
[colors.bright]
black      = "#666666"
red        = "#E60001"
green      = "#0DBC79"
yellow     = "#F7CA09"
blue       = "#0000FF"
magenta    = "#E501E6"
cyan       = "#06E5E5"
white      = "#E5E5E5"
[colors.cursor]
text       = "#FFFFFF"
cursor     = "#0000FF"
[colors.selection]
background = "#B4D7FF"
text       = "CellForeground"
