[colors.primary]
background = '#000000'
foreground = '#FFFFFF'
[colors.normal]
black      = "#000000"
red        = '#FF0000'
green      = '#00FF00'
yellow     = '#FFFF00'
blue       = '#0000FF'
magenta    = '#FF00FF'
cyan       = '#00FFFF'
white      = '#FFFFFF'
[colors.bright]
black      = "#696969"
red        = '#FF0000'
green      = '#00FF00'
yellow     = '#FFFF00'
blue       = '#0000FF'
magenta    = '#FF00FF'
cyan       = '#00FFFF'
white      = '#FFFFFF'
[colors.cursor]
text       = "#000000"
cursor     = "#FFFF00"
[colors.selection]
background = "#304d75"
text       = "CellForeground"
