[colors.primary]
background = '#1e1e1e'
foreground = '#FFFFFF'
[colors.normal]
black      = "#1a1a1a"
red        = "#f97583"
green      = "#378F5D"
yellow     = "#fa8737"
blue       = "#79b8ff"
magenta    = "#a474fc"
cyan       = "#76d6ff"
white      = "#98989d"
[colors.bright]
black      = "#464646"
red        = "#FF7A84"
green      = "#378F5D"
yellow     = "#ffab70"
blue       = "#316bcd"
magenta    = "#b392f0"
cyan       = "#65D9EF"
white      = "#888888"
[colors.cursor]
text       = "#FFFFFF"
cursor     = "#0000FF"
[colors.selection]
background = "#3f638b"
text       = "CellForeground"
# #bf5af2
# #F92572
