[colors.primary]
background = "#30363d"
foreground = "#e6edf3"
[colors.normal]
black      = "#272822"
red        = "#ff7b72"
green      = "#0DBC79"
yellow     = "#d29922"
blue       = "#79c0ff"
magenta    = "#d2a8ff"
cyan       = "#a5d6ff"
white      = "#b1bac4"
[colors.bright]
black      = "#484f58"
red        = "#ff7b72"
green      = "#23D18B"
yellow     = "#e3b341"
blue       = "#79c0ff"
magenta    = "#d2a8ff"
cyan       = "#a5d6ff"
white      = "#b1bac4"
[colors.cursor]
text       = "#FFFFFF"
cursor     = "#ff0000"
[colors.selection]
background = "#304d75"
text       = "CellForeground"
