[colors.primary]
background = "#0d1117"
foreground = "#e6edf3"
[colors.normal]
black      = "#484f58"
red        = "#ff7b72"
green      = "#0DBC79"
yellow     = "#d29922"
blue       = "#58a6ff"
magenta    = "#bc8cff"
cyan       = "#a5d6ff"
white      = "#b1bac4"
[colors.bright]
black      = "#6e7681"
red        = "#ff7b72"
green      = "#23D18B"
yellow     = "#e3b341"
blue       = "#79c0ff"
magenta    = "#bc8cff"
cyan       = "#a5d6ff"
white      = "#b1bac4"
[colors.cursor]
text       = "#FFFFFF"
cursor     = "#ff0000"
[colors.selection]
background = "#17335a"
text       = "CellForeground"
