[colors.primary]
background = "#FFFFFF"
foreground = "#000000"
[colors.normal]
black      = "#000000"
red        = "#F00000"
green      = "#00F000"
yellow     = "#CCCC00"
blue       = "#0000FF"
magenta    = "#FF00FF"
cyan       = "#00FFFF"
white      = "#808080"
[colors.bright]
black      = "#000000"
red        = "#F00000"
green      = "#00F000"
yellow     = "#CCCC00"
blue       = "#0000FF"
magenta    = "#FF00FF"
cyan       = "#00FFFF"
white      = "#808080"
[colors.cursor]
text       = "#FFFFFF"
cursor     = "#0000FF"
[colors.selection]
background = "#DAE9F9"
text       = "CellForeground"
