[colors.primary]
background = '#FFFFFF'
foreground = '#000000'
[colors.normal]
black      = '#000000'
red        = '#FF0000'
green      = '#00FF00'
yellow     = '#CCCC00'
blue       = '#0000FF'
magenta    = '#ff00ff'
cyan       = '#00FFFF'
white      = '#808080'
[colors.bright]
black      = '#000000'
red        = '#FF0000'
green      = '#00FF00'
yellow     = '#CCCC00'
blue       = '#0000FF'
magenta    = '#ff00ff'
cyan       = '#00FFFF'
white      = '#808080'
[colors.selection]
background = "#dae9f9"
text       = "CellForeground"
