[ids]
# FL-CMMK
3151:4011:a2a3d108 
3151:4011:59783b6a 
3151:4011:e9545600 
3151:4011:a36b8bdf 
3151:4011:5b3db59a 

[aliases]
leftmeta = left_cmd
leftcontrol = super_ctrl

[main]
rightmeta=rightmeta
rightalt=rightalt
rightcontrol=rightcontrol
rightshift=rightshift

[chrome:M]
n=C-n
t=C-t
w=C-w
a=C-a
f=C-f
r=C-r
l=C-l
c=C-insert
v=S-insert
x=S-delete
left=home
right=end

[nav:C]
a=home
e=end
p=up
n=down
b=left
f=right
w=C-delete
h=delete
