[ids]
05ac:0341:89b7fedc 

[aliases]
leftmeta = left_cmd
capslock = super_ctrl

[main]
rightmeta=rightmeta
rightalt=rightalt
rightcontrol=rightcontrol
rightshift=rightshift

[chrome:M]
n=C-n
t=C-t
w=C-w
a=C-a
f=C-f
r=C-r
l=C-l
c=C-insert
v=S-insert
x=S-delete
left=home
right=end

[nav:C]
a=home
e=end
p=up
n=down
b=left
f=right
w=C-delete
h=delete
